---
# tasks file for ansible-role-run-docker-gluster
---
- name: Run Jenkins
  docker:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_sr }}"
    state: started
    restart_policy: always
    volumes: "{{ docker_gluster_mount_path }}:{{ docker_container_mount_path }}"
