---
# tasks file for ansible-role-run-docker-gluster

- name: Create user for accessing gluster volume
  user:
    name: "{{ docker_gluster_volume_owner }}"
    uid: "{{ docker_gluster_volume_owner_id }}"
  when: docker_gluster_volume_owner is defined

- name: Change ownernship of gluster volume
  file:
    owner: "{{ docker_gluster_volume_owner }}"
    group: "{{ docker_gluster_volume_owner }}"
    path: "{{ docker_gluster_mount_path }}"
  when: docker_gluster_volume_owner is defined

- name: Install python-pip (dependency of ansible docker module)
  package:
    name: python-pip
    state: latest

- name: Install docker-py (dependency of ansible docker module)
  pip:
    name: docker-py
    version: "{{ docker_py_version }}"

- name: Run container
  docker:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_src }}"
    state: started
    restart_policy: always
    volumes: "{{ docker_gluster_mount_path }}:{{ docker_container_mount_path }}"
    expose:
      - 443

